services:
  user-service:
    image: user-service-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=user-db
      - DATABASE_PORT=5432
    depends_on:
      - user-db
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    working_dir: /app

  user-db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - user-db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  user-db-data:
  pgadmin-data: